[versions]
appVersionCode = "13"
appVersionName = "1.10"
androidGradlePlugin = "8.5.0"
kotlin = "2.0.0"
androidxCore = "1.13.1"
androidxAppCompat = "1.7.0"
androidxConstraintLayout = "2.1.4"
androidxAnnotation = "1.8.0"
googleMaterial = "1.12.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
