name: build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - uses: android-actions/setup-android@v3
      - name: Prepare release keystore
        run: |
          echo "${{ secrets.RELEASE_STORE_FILE_BASE64 }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.RELEASE_STORE_FILE_PASSPHRASE }}" --batch keystore.jks.asc > app/keystore.jks
      - name: Write secrets to gradle.properties
        run: |
          echo "" >> gradle.properties
          echo "PRIVATE_DNS_QS_RELEASE_STORE_FILE=keystore.jks" >> gradle.properties
          echo "PRIVATE_DNS_QS_RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> gradle.properties
          echo "PRIVATE_DNS_QS_RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> gradle.properties
          echo "PRIVATE_DNS_QS_RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> gradle.properties
          echo "" >> gradle.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean assembleRelease --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
